.model tiny ; directiva de modelo de programación
.stack ; directiva de asignación de segmento de stack
.data ; directiva de asignación de segmento de datos
TEXTO DB "CUALQUIER NOMBRE $"
.code ; directiva de asignación de segmento de datos
start: 
begin PROC FAR; INICIO DE PROCEDIMIENTO BEGIN

 MOV AX,0600H ; PETICION
 MOV BH,07H ;ATRIBUTO NEGRO SOBRE BLANCO
 MOV CX,0000H ;INICIO
 MOV DX,184FH ;FINAL
 INT 10H
 
 MOV AH,02H ;PETICIÓN PARA COLOCAR EL CURSOR
 MOV BH,00 ;NÚMERO DE PÁGINA 0
 MOV DH,1 ;RENGLÓN
 MOV DL,1 ;COLUMNA
 INT 10H
 LEA DX,TEXTO ;CARGA DE LA DIRECCION
 MOV AX,SEG TEXTO ; SEGMENTO EN AX
 MOV DS,AX ; DS:DX APUNTA AL MENSAJE
 MOV AH,09H ;PETICIÓN DE DESPLIEGE
 INT 21H ;INTERRUPCIÓN
 
 MOV AH,02H ;PETICIÓN PARA COLOCAR EL CURSOR
 MOV BH,00 ;NÚMERO DE PÁGINA 0
 MOV DH,1 ;RENGLÓN
 MOV DL,55 ;COLUMNA
 INT 10H
 LEA DX,TEXTO ;CARGA DE LA DIRECCION
 MOV AX,SEG TEXTO ; SEGMENTO EN AX
 MOV DS,AX ; DS:DX APUNTA AL MENSAJE
 MOV AH,09H ;PETICIÓN DE DESPLIEGE
 INT 21H ;INTERRUPCIÓN
 
 MOV AH,02H ;PETICIÓN PARA COLOCAR EL CURSOR
 MOV BH,00 ;NÚMERO DE PÁGINA 0
 MOV DH,23 ;RENGLÓN
 MOV DL,1 ;COLUMNA
 INT 10H
 LEA DX,TEXTO ;CARGA DE LA DIRECCION
 MOV AX,SEG TEXTO ; SEGMENTO EN AX
 MOV DS,AX ; DS:DX APUNTA AL MENSAJE
 MOV AH,09H ;PETICIÓN DE DESPLIEGE
 INT 21H ;INTERRUPCIÓN
 
 MOV AH,02H ;PETICIÓN PARA COLOCAR EL CURSOR
 MOV BH,00 ;NÚMERO DE PÁGINA 0
 MOV DH,11 ;RENGLÓN
 MOV DL,27 ;COLUMNA
 INT 10H
 LEA DX,TEXTO ;CARGA DE LA DIRECCION
 MOV AX,SEG TEXTO ; SEGMENTO EN AX
 MOV DS,AX ; DS:DX APUNTA AL MENSAJE
 MOV AH,09H ;PETICIÓN DE DESPLIEGE
 INT 21H ;INTERRUPCIÓN
 
 MOV AH,02H ;PETICIÓN PARA COLOCAR EL CURSOR
 MOV BH,00 ;NÚMERO DE PÁGINA 0
 MOV DH,23 ;RENGLÓN
 MOV DL,55 ;COLUMNA
 INT 10H
 LEA DX,TEXTO ;CARGA DE LA DIRECCION
 MOV AX,SEG TEXTO ; SEGMENTO EN AX
 MOV DS,AX ; DS:DX APUNTA AL MENSAJE
 MOV AH,09H ;PETICIÓN DE DESPLIEGE
 INT 21H ;INTERRUPCIÓN
 
 CALL PAUSA
 MOV AX,4C00H ; vuelta al DOS
 INT 21H ;INTERRUPCIÓN
 
PAUSA PROC NEAR
 MOV AH, 10h ; PAUSA
 INT 16h
 RET
PAUSA ENDP
BEGIN ENDP ;FIN DE PROCEDIMIENTO
END start ;FIN DE PROGRAMA
